### ISSUE TITLE
Toast Messages needed

### ISSUE THREAD

**Issue by aryad14** [mlscgescoe/streambox#1]
## Issue
When user logs in or registers, there is not Alert messages shown for successful login or any error occurance.

## Expected Solution
To display such alerts, libraries like [React Hot Toast](https://react-hot-toast.com/) and [React Toastify](https://fkhadra.github.io/react-toastify/introduction) can be used.

Thank you!

**Comment by Rahulagg13** [comment]
hey can you assign this issue to me?
